name: Update Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
          cd pr_review
          docker build -t openrhino/pr-review-gpt .
          docker push openrhino/pr-review-gpt
          cd ..

    - name: Set up Kubernetes environment
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Restart Deployment
      run: kubectl rollout restart deployment pr-review-gpt
